default: &default
  adapter: postgresql
  pool: 5
  timeout: 5000
  username: <%= ENV["DB_USERNAME"] %>
  password: <%= ENV["DB_PASSWORD"] %>

development:
  <<: *default
  database: adwords_dev

test:
  <<: *default
  database: adwords_test

production:
  <<: *default
  database: adwords_pro
