  # This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ name: 'Chicago' }, { name: 'Copenhagen' }])
#   Mayor.create(name: 'Emanuel', city: cities.first)

country_list = [
  ["Afghanistan", "AF"],
  ["Albania", "AL"],
  ["Algeria", "DZ"],
  ["American Samoa", "AS"],
  ["Andorra", "AD"],
  ["Angola", "AO"],
  ["Anguilla", "AI"],
  ["Antarctica", "AQ"],
  ["Antigua and Barbuda", "AG"],
  ["Argentina", "AR"],
  ["Armenia", "AM"],
  ["Aruba", "AW"],
  ["Australia", "AU"],
  ["Austria", "AT"],
  ["Azerbaijan", "AZ"],
  ["Bahamas", "BS"],
  ["Bahrain", "BH"],
  ["Bangladesh", "BD"],
  ["Barbados", "BB"],
  ["Belarus", "BY"],
  ["Belgium", "BE"],
  ["Belize", "BZ"],
  ["Benin", "BJ"],
  ["Bermuda", "BM"],
  ["Bhutan", "BT"],
  ["Bolivia", "BO"],
  ["Bosnia and Herzegovina", "BA"],
  ["Botswana", "BW"],
  ["Brazil", "BR"],
  ["British Indian Ocean Territory", "IO"],
  ["Brunei Darussalam", "BN"],
  ["Bulgaria", "BG"],
  ["Burkina Faso", "BF"],
  ["Burundi", "BI"],
  ["Cambodia", "KH"],
  ["Cameroon", "CM"],
  ["Canada", "CA"],
  ["Cape Verde", "CV"],
  ["Cayman Islands", "KY"],
  ["Central African Republic", "CF"],
  ["Chad", "TD"],
  ["Chile", "CL"],
  ["China", "CN"],
  ["Christmas Island", "CX"],
  ["Cocos (Keeling) Islands", "CC"],
  ["Colombia", "CO"],
  ["Comoros", "KM"],
  ["Congo", "CG"],
  ["Congo, Democratic Republic", "CD"],
  ["Cook Islands", "CK"],
  ["Costa Rica", "CR"],
  ["Cote d'Ivoire", "CI"],
  ["Croatia", "HR"],
  ["Cyprus", "CY"],
  ["Czech Republic", "CZ"],
  ["Denmark", "DK"],
  ["Djibouti", "DJ"],
  ["Dominica", "DM"],
  ["Dominican Republic", "DO"],
  ["East Timor", "TL"],
  ["Ecuador", "EC"],
  ["Egypt", "EG"],
  ["El Salvador", "SV"],
  ["Equatorial Guinea", "GQ"],
  ["Eritrea", "ER"],
  ["Estonia", "EE"],
  ["Ethiopia", "ET"],
  ["Falkland Islands (Malvinas)", "FK"],
  ["Faroe Islands", "FO"],
  ["Fiji", "FJ"],
  ["Finland", "FI"],
  ["France", "FR"],
  ["French Guiana", "GF"],
  ["French Polynesia", "PF"],
  ["French Southern Territories", "TF"],
  ["Gabon", "GA"],
  ["Gambia", "GM"],
  ["Georgia", "GE"],
  ["Germany", "DE"],
  ["Ghana", "GH"],
  ["Gibraltar", "GI"],
  ["Greece", "GR"],
  ["Greenland", "GL"],
  ["Grenada", "GD"],
  ["Guadeloupe", "GP"],
  ["Guam", "GU"],
  ["Guatemala", "GT"],
  ["Guinea", "GN"],
  ["Guinea-Bissau", "GW"],
  ["Guyana", "GY"],
  ["Haiti", "HT"],
  ["Honduras", "HN"],
  ["Hong Kong", "HK"],
  ["Hungary", "HU"],
  ["Iceland", "IS"],
  ["India", "IN"],
  ["Indonesia", "ID"],
  ["Iraq", "IQ"],
  ["Ireland", "IE"],
  ["Israel", "IL"],
  ["Italy", "IT"],
  ["Jamaica", "JM"],
  ["Japan", "JP"],
  ["Jordan", "JO"],
  ["Kazakhstan", "KZ"],
  ["Kenya", "KE"],
  ["Kiribati", "KI"],
  ["Kuwait", "KW"],
  ["Kyrgyzstan", "KG"],
  ["Lao People's Democratic Republic", "LA"],
  ["Latvia", "LV"],
  ["Lebanon", "LB"],
  ["Lesotho", "LS"],
  ["Liberia", "LR"],
  ["Libya", "LY"],
  ["Liechtenstein", "LI"],
  ["Lithuania", "LT"],
  ["Luxembourg", "LU"],
  ["Macau", "MO"],
  ["Macedonia", "MK"],
  ["Madagascar", "MG"],
  ["Malawi", "MW"],
  ["Malaysia", "MY"],
  ["Maldives", "MV"],
  ["Mali", "ML"],
  ["Malta", "MT"],
  ["Marshall Islands", "MH"],
  ["Martinique", "MQ"],
  ["Mauritania", "MR"],
  ["Mauritius", "MU"],
  ["Mayotte", "YT"],
  ["Mexico", "MX"],
  ["Micronesia", "FM"],
  ["Moldova", "MD"],
  ["Monaco", "MC"],
  ["Mongolia", "MN"],
  ["Montenegro", "ME"],
  ["Montserrat", "MS"],
  ["Morocco", "MA"],
  ["Mozambique", "MZ"],
  ["Namibia", "NA"],
  ["Nauru", "NR"],
  ["Nepal", "NP"],
  ["Netherlands", "NL"],
  ["Netherlands Antilles", "AN"],
  ["New Caledonia", "NC"],
  ["New Zealand", "NZ"],
  ["Nicaragua", "NI"],
  ["Niger", "NE"],
  ["Nigeria", "NG"],
  ["Niue", "NU"],
  ["Norfolk Island", "NF"],
  ["Northern Mariana Islands", "MP"],
  ["Norway", "NO"],
  ["Oman", "OM"],
  ["Pakistan", "PK"],
  ["Palau", "PW"],
  ["Palestinian Territory", "PS"],
  ["Panama", "PA"],
  ["Papua New Guinea", "PG"],
  ["Paraguay", "PY"],
  ["Peru", "PE"],
  ["Philippines", "PH"],
  ["Pitcairn", "PN"],
  ["Poland", "PL"],
  ["Portugal", "PT"],
  ["Puerto Rico", "PR"],
  ["Qatar", "QA"],
  ["Republic of Kosovo", "XK"],
  ["Reunion", "RE"],
  ["Romania", "RO"],
  ["Russian Federation", "RU"],
  ["Rwanda", "RW"],
  ["Saint Kitts and Nevis", "KN"],
  ["Saint Lucia", "LC"],
  ["Saint Vincent and the Grenadines", "VC"],
  ["Samoa", "WS"],
  ["San Marino", "SM"],
  ["Sao Tome and Principe", "ST"],
  ["Saudi Arabia", "SA"],
  ["Senegal", "SN"],
  ["Serbia", "RS"],
  ["Seychelles", "SC"],
  ["Sierra Leone", "SL"],
  ["Singapore", "SG"],
  ["Slovakia", "SK"],
  ["Slovenia", "SI"],
  ["Solomon Islands", "SB"],
  ["Somalia", "SO"],
  ["South Africa", "ZA"],
  ["South Georgia and The South Sandwich Islands", "GS"],
  ["South Korea", "KR"],
  ["Spain", "ES"],
  ["Sri Lanka", "LK"],
  ["St. Helena", "SH"],
  ["St. Pierre and Miquelon", "PM"],
  ["Suriname", "SR"],
  ["Svalbard and Jan Mayen Islands", "SJ"],
  ["Swaziland", "SZ"],
  ["Sweden", "SE"],
  ["Switzerland", "CH"],
  ["Taiwan", "TW"],
  ["Tajikistan", "TJ"],
  ["Tanzania", "TZ"],
  ["Thailand", "TH"],
  ["Togo", "TG"],
  ["Tokelau", "TK"],
  ["Tonga", "TO"],
  ["Trinidad and Tobago", "TT"],
  ["Tunisia", "TN"],
  ["Turkey", "TR"],
  ["Turkmenistan", "TM"],
  ["Turks and Caicos Islands", "TC"],
  ["Tuvalu", "TV"],
  ["Uganda", "UG"],
  ["Ukraine", "UA"],
  ["United Arab Emirates", "AE"],
  ["United Kingdom", "GB"],
  ["United States", "US"],
  ["United States Minor Outlying Islands", "UM"],
  ["Uruguay", "UY"],
  ["Uzbekistan", "UZ"],
  ["Vanuatu", "VU"],
  ["Vatican", "VA"],
  ["Venezuela", "VE"],
  ["Viet Nam", "VN"],
  ["Virgin Islands (British)", "VG"],
  ["Virgin Islands (U.S.)", "VI"],
  ["Wallis and Futuna Islands", "WF"],
  ["Western Sahara", "EH"],
  ["Yemen", "YE"],
  ["Zambia", "ZM"],
  ["Zimbabwe", "ZW"]
]

time_zone_list = [
  ["(GMT+04:30) Kabul", "Asia/Kabul", "AF"],
  ["(GMT+02:00) Tirane", "Europe/Tirane", "AL"],
  ["(GMT+01:00) Algiers", "Africa/Algiers", "DZ"],
  ["(GMT-11:00) Pago Pago", "Pacific/Pago_Pago", "AS"],
  ["(GMT+02:00) Andorra", "Europe/Andorra", "AD"],
  ["(GMT+01:00) Lagos", "Africa/Lagos", "AO"],
  ["(GMT-04:00) Port of Spain", "America/Port_of_Spain", "AI"],

  ["Now select a timezone:", "", "AQ"],
  ["(GMT-03:00) Palmer", "Antarctica/Palmer", "AQ"],
  ["(GMT-03:00) Rothera", "Antarctica/Rothera", "AQ"],
  ["(GMT+03:00) Syowa", "Antarctica/Syowa", "AQ"],
  ["(GMT+05:00) Mawson", "Antarctica/Mawson", "AQ"],
  ["(GMT+06:00) Vostok", "Antarctica/Vostok", "AQ"],
  ["(GMT+07:00) Davis", "Antarctica/Davis", "AQ"],
  ["(GMT+08:00) Casey", "Antarctica/Casey", "AQ"],
  ["(GMT+10:00) Dumont D'Urville", "Antarctica/DumontDUrville", "AQ"],
  ["(GMT+12:00) Auckland", "Pacific/Auckland", "AQ"],

  ["(GMT-04:00) Port of Spain", "America/Port_of_Spain", "AG"],
  ["(GMT-03:00) Buenos Aires", "America/Argentina/Buenos_Aires", "AR"],
  ["(GMT+04:00) Yerevan", "Asia/Yerevan", "AM"],
  ["(GMT-04:00) Curacao", "America/Curacao", "AW"],
  
  ["Now select a timezone:", "", "AU"],
  ["(GMT+08:00) Western Time - Perth", "Australia/Perth", "AU"],
  ["(GMT+08:45) Australian Central Western Standard Time", "Australia/Eucla", "AU"],
  ["(GMT+09:30) Central Time - Adelaide", "Australia/Adelaide", "AU"],
  ["(GMT+09:30) Central Time - Darwin", "Australia/Darwin", "AU"],
  ["(GMT+10:00) Eastern Time - Brisbane", "Australia/Brisbane", "AU"],
  ["(GMT+10:00) Eastern Time - Hobart", "Australia/Hobart", "AU"],
  ["(GMT+10:00) Eastern Time - Melbourne, Sydney", "Australia/Sydney", "AU"],

  ["(GMT+02:00) Vienna", "Europe/Vienna", "AT"],
  ["(GMT+04:00) Baku", "Asia/Baku", "AZ"],
  ["(GMT-04:00) Nassau", "America/Nassau", "BS"],
  ["(GMT+03:00) Qatar", "Asia/Qatar", "BH"],
  ["(GMT+06:00) Dhaka", "Asia/Dhaka", "BD"],
  ["(GMT-04:00) Barbados", "America/Barbados", "BB"],
  ["(GMT+03:00) Minsk", "Europe/Minsk", "BY"],
  ["(GMT+02:00) Brussels", "Europe/Brussels", "BE"],
  ["(GMT-06:00) Belize", "America/Belize", "BZ"],
  ["(GMT+01:00) Lagos", "Africa/Lagos", "BJ"],
  ["(GMT-03:00) Bermuda", "Atlantic/Bermuda", "BM"],
  ["(GMT+06:00) Thimphu", "Asia/Thimphu", "BT"],
  ["(GMT-04:00) La Paz", "America/La_Paz", "BO"],
  ["(GMT+02:00) Central European Time - Belgrade", "Europe/Belgrade", "BA"],
  ["(GMT+02:00) Maputo", "Africa/Maputo", "BW"],
  
  ["Now select a timezone:", "", "BR"],
  ["(GMT-02:00) Noronha", "America/Noronha", "BR"],
  ["(GMT-03:00) Araguaina", "America/Araguaina", "BR"],
  ["(GMT-03:00) Belem", "America/Belem", "BR"],
  ["(GMT-03:00) Fortaleza", "America/Fortaleza", "BR"],
  ["(GMT-03:00) Maceio", "America/Maceio", "BR"],
  ["(GMT-03:00) Recife", "America/Recife", "BR"],
  ["(GMT-03:00) Salvador", "America/Bahia", "BR"],
  ["(GMT-03:00) Sao Paulo", "America/Sao_Paulo", "BR"],
  ["(GMT-04:00) Boa Vista", "America/Boa_Vista", "BR"],
  ["(GMT-04:00) Campo Grande", "America/Campo_Grande", "BR"],
  ["(GMT-04:00) Cuiaba", "America/Cuiaba", "BR"],
  ["(GMT-04:00) Manaus", "America/Manaus", "BR"],
  ["(GMT-04:00) Porto Velho", "America/Porto_Velho", "BR"],
  ["(GMT-05:00) Rio Branco", "America/Rio_Branco", "BR"],

  ["(GMT+06:00) Chagos", "Indian/Chagos", "IO"],
  ["(GMT+08:00) Brunei", "Asia/Brunei", "BN"],
  ["(GMT+03:00) Sofia", "Europe/Sofia", "BG"],
  ["(GMT+00:00) Abidjan", "Africa/Abidjan", "BF"],
  ["(GMT+02:00) Maputo", "Africa/Maputo", "BI"],
  ["(GMT+07:00) Bangkok", "Asia/Bangkok", "KH"],
  ["(GMT+01:00) Lagos", "Africa/Lagos", "CM"],

  ["Now select a timezone:", "", "CA"],
  ["(GMT-02:30) Newfoundland Time - St. Johns", "America/St_Johns", "CA"],
  ["(GMT-03:00) Atlantic Time - Halifax", "America/Halifax", "CA"],
  ["(GMT-04:00) Eastern Time - Iqaluit", "America/Iqaluit", "CA"],
  ["(GMT-04:00) Eastern Time - Toronto", "America/Toronto", "CA"],
  ["(GMT-05:00) Central Time - Winnipeg", "America/Winnipeg", "CA"],
  ["(GMT-06:00) Central Time - Regina", "America/Regina", "CA"],
  ["(GMT-06:00) Mountain Time - Edmonton", "America/Edmonton", "CA"],
  ["(GMT-06:00) Mountain Time - Yellowknife", "America/Yellowknife", "CA"],
  ["(GMT-07:00) Mountain Time - Dawson Creek", "America/Dawson_Creek", "CA"],
  ["(GMT-07:00) Pacific Time - Vancouver", "America/Vancouver", "CA"],
  ["(GMT-07:00) Pacific Time - Whitehorse", "America/Whitehorse", "CA"],

  ["(GMT-01:00) Cape Verde", "Atlantic/Cape_Verde", "CV"],
  ["(GMT-05:00) Panama", "America/Panama", "KY"],
  ["(GMT+01:00) Lagos", "Africa/Lagos", "CF"],
  ["(GMT+01:00) Ndjamena", "Africa/Ndjamena", "TD"],

  ["Now select a timezone:", "", "CL"],
  ["(GMT-03:00) Santiago", "America/Santiago", "CL"],
  ["(GMT-05:00) Easter Island", "Pacific/Easter", "CL"],

  ["(GMT+08:00) China Time - Beijing", "Asia/Shanghai", "CN"],
  ["(GMT+07:00) Christmas", "Indian/Christmas", "CX"],
  ["(GMT+06:30) Cocos", "Indian/Cocos", "CC"],
  ["(GMT-05:00) Bogota", "America/Bogota", "CO"],
  ["(GMT+03:00) Nairobi", "Africa/Nairobi", "KM"],
  ["(GMT+01:00) Lagos", "Africa/Lagos", "CG"],
  
  ["Now select a timezone:", "", "CD"],
  ["(GMT+01:00) Lagos", "Africa/Lagos", "CD"],
  ["(GMT+02:00) Maputo", "Africa/Maputo", "CD"],

  ["Now select a timezone:", "", "CR"],
  ["(GMT-10:00) Rarotonga", "Pacific/Rarotonga", "CK"],
  ["(GMT-06:00) Costa Rica", "America/Costa_Rica", "CR"],

  ["(GMT+00:00) Abidjan", "Africa/Abidjan", "CI"],
  ["(GMT+02:00) Central European Time - Belgrade", "Europe/Belgrade", "HR"],
  ["(GMT+03:00) Nicosia", "Asia/Nicosia", "CY"],
  ["(GMT+02:00) Central European Time - Prague", "Europe/Prague", "CZ"],
  ["(GMT+02:00) Copenhagen", "Europe/Copenhagen", "DK"],
  ["(GMT+03:00) Nairobi", "Africa/Nairobi", "DJ"],
  ["(GMT-04:00) Port of Spain", "America/Port_of_Spain", "DM"],
  ["(GMT-04:00) Santo Domingo", "America/Santo_Domingo", "DO"],
  ["(GMT+09:00) Dili", "Asia/Dili", "TL"],

  ["Now select a timezone:", "", "EC"],
  ["(GMT-05:00) Guayaquil", "America/Guayaquil", "EC"],
  ["(GMT-06:00) Galapagos", "Pacific/Galapagos", "EC"],

  ["(GMT+02:00) Cairo", "Africa/Cairo", "EG"],
  ["(GMT-06:00) El Salvador", "America/El_Salvador", "SV"],
  ["(GMT+01:00) Lagos", "Africa/Lagos", "GQ"],
  ["(GMT+03:00) Nairobi", "Africa/Nairobi", "ER"],
  ["(GMT+03:00) Tallinn", "Europe/Tallinn", "EE"],
  ["(GMT+03:00) Nairobi", "Africa/Nairobi", "ET"],
  ["(GMT-03:00) Stanley", "Atlantic/Stanley", "FK"],
  ["(GMT+01:00) Faeroe", "Atlantic/Faroe", "FO"],
  ["(GMT+12:00) Fiji", "Pacific/Fiji", "FJ"],
  ["(GMT+03:00) Helsinki", "Europe/Helsinki", "FI"],
  ["(GMT+02:00) Paris", "Europe/Paris", "FR"],
  ["(GMT-03:00) Cayenne", "America/Cayenne", "GF"],
  
  ["Now select a timezone:", "", "PF"],
  ["(GMT-09:00) Gambier", "Pacific/Gambier", "PF"],
  ["(GMT-09:30) Marquesas", "Pacific/Marquesas", "PF"],
  ["(GMT-10:00) Tahiti", "Pacific/Tahiti", "PF"],
  
  ["(GMT+05:00) Kerguelen", "Indian/Kerguelen", "TF"],
  ["(GMT+01:00) Lagos", "Africa/Lagos", "GA"],
  ["(GMT+00:00) Abidjan", "Africa/Abidjan", "GM"],
  ["(GMT+04:00) Tbilisi", "Asia/Tbilisi", "GE"],
  ["(GMT+02:00) Berlin", "Europe/Berlin", "DE"],
  ["(GMT+00:00) Accra", "Africa/Accra", "GH"],
  ["(GMT+02:00) Gibraltar", "Europe/Gibraltar", "GI"],
  ["(GMT+03:00) Athens", "Europe/Athens", "GR"],
  
  ["Now select a timezone:", "", "GL"],
  ["(GMT-02:00) Godthab", "America/Godthab", "GL"],
  ["(GMT-03:00) Thule", "America/Thule", "GL"],
  ["(GMT+00:00) Danmarkshavn", "America/Danmarkshavn", "GL"],
  ["(GMT+00:00) Scoresbysund", "America/Scoresbysund", "GL"],

  ["(GMT-04:00) Port of Spain", "America/Port_of_Spain", "GD"],
  ["(GMT-04:00) Port of Spain", "America/Port_of_Spain", "GP"],
  ["(GMT+10:00) Guam", "Pacific/Guam", "GU"],
  ["(GMT-06:00) Guatemala", "America/Guatemala", "GT"],
  ["(GMT+00:00) Abidjan", "Africa/Abidjan", "GN"],
  ["(GMT+00:00) Bissau", "Africa/Bissau", "GW"],
  ["(GMT-04:00) Guyana", "America/Guyana", "GY"],
  ["(GMT-05:00) Port-au-Prince", "America/Port-au-Prince", "HT"],
  ["(GMT-06:00) Central Time - Tegucigalpa", "America/Tegucigalpa", "HN"],
  ["(GMT+08:00) Hong Kong", "Asia/Hong_Kong", "HK"],
  ["(GMT+02:00) Budapest", "Europe/Budapest", "HU"],
  ["(GMT+00:00) Reykjavik", "Atlantic/Reykjavik", "IS"],
  ["(GMT+05:30) India Standard Time", "Asia/Calcutta", "IN"],

  ["Now select a timezone:", "", "ID"],
  ["(GMT+07:00) Jakarta", "Asia/Jakarta", "ID"],
  ["(GMT+08:00) Makassar", "Asia/Makassar", "ID"],
  ["(GMT+09:00) Jayapura", "Asia/Jayapura", "ID"],

  ["(GMT+03:00) Baghdad", "Asia/Baghdad", "IQ"],
  ["(GMT+01:00) Dublin", "Europe/Dublin", "IE"],
  ["(GMT+03:00) Jerusalem", "Asia/Jerusalem", "IL"],
  ["(GMT+02:00) Rome", "Europe/Rome", "IT"],
  ["(GMT-05:00) Jamaica", "America/Jamaica", "JM"],
  ["(GMT+09:00) Tokyo", "Asia/Tokyo", "JP"],
  ["(GMT+03:00) Amman", "Asia/Amman", "JO"],
  
  ["Now select a timezone:", "", "KZ"],
  ["(GMT+05:00) Aqtau", "Asia/Aqtau", "KZ"],
  ["(GMT+05:00) Aqtobe", "Asia/Aqtobe", "KZ"],
  ["(GMT+06:00) Almaty", "Asia/Almaty", "KZ"],

  ["(GMT+03:00) Nairobi", "Africa/Nairobi", "KE"],
  
  ["Now select a timezone:", "", "KI"],
  ["(GMT+12:00) Tarawa", "Pacific/Tarawa", "KI"],
  ["(GMT+14:00) Kiritimati", "Pacific/Kiritimati", "KI"],
  
  ["(GMT+03:00) Riyadh", "Asia/Riyadh", "KW"],
  ["(GMT+06:00) Bishkek", "Asia/Bishkek", "KG"],
  ["(GMT+07:00) Bangkok", "Asia/Bangkok", "LA"],
  ["(GMT+03:00) Riga", "Europe/Riga", "LV"],
  ["(GMT+03:00) Beirut", "Asia/Beirut", "LB"],
  ["(GMT+02:00) Johannesburg", "Africa/Johannesburg", "LS"],
  ["(GMT+00:00) Monrovia", "Africa/Monrovia", "LR"],
  ["(GMT+02:00) Tripoli", "Africa/Tripoli", "LY"],
  ["(GMT+02:00) Zurich", "Europe/Zurich", "LI"],
  ["(GMT+03:00) Vilnius", "Europe/Vilnius", "LT"],
  ["(GMT+02:00) Luxembourg", "Europe/Luxembourg", "LU"],
  ["(GMT+08:00) Macau", "Asia/Macau", "MO"],
  ["(GMT+02:00) Central European Time - Belgrade", "Europe/Belgrade", "MK"],
  ["(GMT+03:00) Nairobi", "Africa/Nairobi", "MG"],
  ["(GMT+02:00) Maputo", "Africa/Maputo", "MW"],
  ["(GMT+08:00) Kuala Lumpur", "Asia/Kuala_Lumpur", "MY"],
  ["(GMT+05:00) Maldives", "Indian/Maldives", "MV"],
  ["(GMT+00:00) Abidjan", "Africa/Abidjan", "ML"],
  ["(GMT+02:00) Malta", "Europe/Malta", "MT"],

  ["Now select a timezone:", "", "MH"],
  ["(GMT+12:00) Kwajalein", "Pacific/Kwajalein", "MH"],
  ["(GMT+12:00) Majuro", "Pacific/Majuro", "MH"],

  ["(GMT-04:00) Martinique", "America/Martinique", "MQ"],
  ["(GMT+00:00) Abidjan", "Africa/Abidjan", "MR"],
  ["(GMT+04:00) Mauritius", "Indian/Mauritius", "MU"],
  ["(GMT+03:00) Nairobi", "Africa/Nairobi", "YT"],
  
  ["Now select a timezone:", "", "MX"],
  ["(GMT-05:00) Central Time - Mexico City", "America/Mexico_City", "MX"],
  ["(GMT-06:00) Mountain Time - Chihuahua, Mazatlan", "America/Mazatlan", "MX"],
  ["(GMT-07:00) Mountain Time - Hermosillo", "America/Hermosillo", "MX"],
  ["(GMT-07:00) Pacific Time - Tijuana", "America/Tijuana", "MX"],

  ["Now select a timezone:", "", "FM"],
  ["(GMT+10:00) Truk", "Pacific/Chuuk", "FM"],
  ["(GMT+11:00) Kosrae", "Pacific/Kosrae", "FM"],
  ["(GMT+11:00) Ponape", "Pacific/Pohnpei", "FM"],

  ["(GMT+03:00) Chisinau", "Europe/Chisinau", "MD"],
  ["(GMT+02:00) Monaco", "Europe/Monaco", "MC"],
  
  ["Now select a timezone:", "", "MN"],
  ["(GMT+08:00) Hovd", "Asia/Hovd", "MN"],
  ["(GMT+09:00) Choibalsan", "Asia/Choibalsan", "MN"],
  ["(GMT+09:00) Ulaanbaatar", "Asia/Ulaanbaatar", "MN"],

  ["(GMT+02:00) Central European Time - Belgrade", "Europe/Belgrade", "ME"],
  ["(GMT-04:00) Port of Spain", "America/Port_of_Spain", "MS"],
  ["(GMT+01:00) Casablanca", "Africa/Casablanca", "MA"],
  ["(GMT+02:00) Maputo", "Africa/Maputo", "MZ"],
  ["(GMT+01:00) Windhoek", "Africa/Windhoek", "NA"],
  ["(GMT+12:00) Nauru", "Pacific/Nauru", "NR"],
  ["(GMT+05:45) Katmandu", "Asia/Katmandu", "NP"],
  ["(GMT+02:00) Amsterdam", "Europe/Amsterdam", "NL"],
  ["(GMT-04:00) Curacao", "America/Curacao", "AN"],
  ["(GMT+11:00) Noumea", "Pacific/Noumea", "NC"],
  
  ["Now select a timezone:", "", "NZ"],
  ["(GMT+12:00) Auckland", "Pacific/Auckland", "NZ"],
  ["(GMT+12:45) Chatham Standard Time", "Pacific/Chatham", "NZ"],

  ["(GMT-06:00) Managua", "America/Managua", "NI"],
  ["(GMT+01:00) Lagos", "Africa/Lagos", "NE"],
  ["(GMT+01:00) Lagos", "Africa/Lagos", "NG"],
  ["(GMT-11:00) Niue", "Pacific/Niue", "NU"],
  ["(GMT+11:00) Norfolk", "Pacific/Norfolk", "NF"],
  ["(GMT+10:00) Guam", "Pacific/Guam", "MP"],
  ["(GMT+02:00) Oslo", "Europe/Oslo", "NO"],
  ["(GMT+04:00) Dubai", "Asia/Dubai", "OM"],
  ["(GMT+05:00) Karachi", "Asia/Karachi", "PK"],
  ["(GMT+09:00) Palau", "Pacific/Palau", "PW"],
  ["(GMT+03:00) Gaza", "Asia/Gaza", "PS"],
  ["(GMT-05:00) Panama", "America/Panama", "PA"],
  ["(GMT+10:00) Port Moresby", "Pacific/Port_Moresby", "PG"],
  ["(GMT-04:00) Asuncion", "America/Asuncion", "PY"],
  ["(GMT-05:00) Lima", "America/Lima", "PE"],
  ["(GMT+08:00) Manila", "Asia/Manila", "PH"],
  ["(GMT-08:00) Pitcairn", "Pacific/Pitcairn", "PN"],
  ["(GMT+02:00) Warsaw", "Europe/Warsaw", "PL"],
  
  ["Now select a timezone:", "", "PT"],
  ["(GMT+00:00) Azores", "Atlantic/Azores", "PT"],
  ["(GMT+01:00) Lisbon", "Europe/Lisbon", "PT"],

  ["(GMT-04:00) Puerto Rico", "America/Puerto_Rico", "PR"],
  ["(GMT+03:00) Qatar", "Asia/Qatar", "QA"],
  ["(GMT+02:00) Central European Time - Belgrade", "Europe/Belgrade", "XK"],
  ["(GMT+04:00) Reunion", "Indian/Reunion", "RE"],
  ["(GMT+03:00) Bucharest", "Europe/Bucharest", "RO"],
  
  ["Now select a timezone:", "", "RU"],
  ["(GMT+02:00) Moscow-01 - Kaliningrad", "Europe/Kaliningrad", "RU"],
  ["(GMT+03:00) Moscow+00 - Moscow", "Europe/Moscow", "RU"],
  ["(GMT+04:00) Moscow+01 - Samara", "Europe/Samara", "RU"],
  ["(GMT+05:00) Moscow+02 - Yekaterinburg", "Asia/Yekaterinburg", "RU"],
  ["(GMT+06:00) Moscow+03 - Omsk, Novosibirsk", "Asia/Omsk", "RU"],
  ["(GMT+07:00) Moscow+04 - Krasnoyarsk", "Asia/Krasnoyarsk", "RU"],
  ["(GMT+08:00) Moscow+05 - Irkutsk", "Asia/Irkutsk", "RU"],
  ["(GMT+09:00) Moscow+06 - Yakutsk", "Asia/Yakutsk", "RU"],
  ["(GMT+10:00) Moscow+07 - Yuzhno-Sakhalinsk", "Asia/Vladivostok", "RU"],
  ["(GMT+11:00) Moscow+07 - Magadan", "Asia/Magadan", "RU"],
  ["(GMT+12:00) Moscow+09 - Petropavlovsk-Kamchatskiy", "Asia/Kamchatka", "RU"],

  ["(GMT+02:00) Maputo", "Africa/Maputo", "RW"],
  ["(GMT-04:00) Port of Spain", "America/Port_of_Spain", "KN"],
  ["(GMT-04:00) Port of Spain", "America/Port_of_Spain", "LC"],
  ["(GMT-04:00) Port of Spain", "America/Port_of_Spain", "VC"],
  ["(GMT+13:00) Apia", "Pacific/Apia", "WS"],
  ["(GMT+02:00) Rome", "Europe/Rome", "SM"],
  ["(GMT+00:00) Abidjan", "Africa/Abidjan", "ST"],
  ["(GMT+03:00) Riyadh", "Asia/Riyadh", "SA"],
  ["(GMT+00:00) Abidjan", "Africa/Abidjan", "SN"],
  ["(GMT+02:00) Central European Time - Belgrade", "Europe/Belgrade", "RS"],
  ["(GMT+04:00) Mahe", "Indian/Mahe", "SC"],
  ["(GMT+00:00) Abidjan", "Africa/Abidjan", "SL"],
  ["(GMT+08:00) Singapore", "Asia/Singapore", "SG"],
  ["(GMT+02:00) Central European Time - Prague", "Europe/Prague", "SK"],
  ["(GMT+02:00) Central European Time - Belgrade", "Europe/Belgrade", "SI"],
  ["(GMT+11:00) Guadalcanal", "Pacific/Guadalcanal", "SB"],
  ["(GMT+03:00) Nairobi", "Africa/Nairobi", "SO"],
  ["(GMT+02:00) Johannesburg", "Africa/Johannesburg", "ZA"],
  ["(GMT-02:00) South Georgia", "Atlantic/South_Georgia", "GS"],
  ["(GMT+09:00) Seoul", "Asia/Seoul", "KR"],

  ["Now select a timezone:", "", "ES"],
  ["(GMT+01:00) Canary Islands", "Atlantic/Canary", "ES"],
  ["(GMT+02:00) Ceuta", "Africa/Ceuta", "ES"],
  ["(GMT+02:00) Madrid", "Europe/Madrid", "ES"],

  ["(GMT+05:30) Colombo", "Asia/Colombo", "LK"],
  ["(GMT+00:00) Abidjan", "Africa/Abidjan", "SH"],
  ["(GMT-02:00) Miquelon", "America/Miquelon", "PM"],
  ["(GMT-03:00) Paramaribo", "America/Paramaribo", "SR"],
  ["(GMT+02:00) Oslo", "Europe/Oslo", "SJ"],
  ["(GMT+02:00) Johannesburg", "Africa/Johannesburg", "SZ"],
  ["(GMT+02:00) Stockholm", "Europe/Stockholm", "SE"],
  ["(GMT+02:00) Zurich", "Europe/Zurich", "CH"],
  ["(GMT+08:00) Taipei", "Asia/Taipei", "TW"],
  ["(GMT+05:00) Dushanbe", "Asia/Dushanbe", "TJ"],
  ["(GMT+03:00) Nairobi", "Africa/Nairobi", "TZ"],
  ["(GMT+07:00) Bangkok", "Asia/Bangkok", "TH"],
  ["(GMT+00:00) Abidjan", "Africa/Abidjan", "TG"],
  ["(GMT+13:00) Fakaofo", "Pacific/Fakaofo", "TK"],
  ["(GMT+13:00) Tongatapu", "Pacific/Tongatapu", "TO"],
  ["(GMT-04:00) Port of Spain", "America/Port_of_Spain", "TT"],
  ["(GMT+01:00) Tunis", "Africa/Tunis", "TN"],
  ["(GMT+03:00) Istanbul", "Europe/Istanbul", "TR"],
  ["(GMT+05:00) Ashgabat", "Asia/Ashgabat", "TM"],
  ["(GMT-04:00) Grand Turk", "America/Grand_Turk", "TC"],
  ["(GMT+12:00) Funafuti", "Pacific/Funafuti", "TV"],
  ["(GMT+03:00) Nairobi", "Africa/Nairobi", "UG"],
  ["(GMT+03:00) Kiev", "Europe/Kiev", "UA"],
  ["(GMT+04:00) Dubai", "Asia/Dubai", "AE"],
  
  ["Now select a timezone:", "", "GB"],
  ["(GMT+00:00) GMT (no daylight saving)", "Etc/GMT", "GB"],
  ["(GMT+01:00) London", "Europe/London", "GB"],

  ["Now select a timezone:", "", "US"],
  ["(GMT-04:00) Eastern Time", "America/New_York", "US"],
  ["(GMT-05:00) Central Time", "America/Chicago", "US"],
  ["(GMT-06:00) Mountain Time", "America/Denver", "US"],
  ["(GMT-07:00) Mountain Time - Arizona", "America/Phoenix", "US"],
  ["(GMT-07:00) Pacific Time", "America/Los_Angeles", "US"],
  ["(GMT-08:00) Alaska Time", "America/Anchorage", "US"],
  ["(GMT-10:00) Hawaii Time", "Pacific/Honolulu", "US"],

  ["Now select a timezone:", "", "UM"],
  ["(GMT-10:00) Hawaii Time", "Pacific/Honolulu", "UM"],
  ["(GMT-11:00) Pago Pago", "Pacific/Pago_Pago", "UM"],
  ["(GMT+12:00) Wake", "Pacific/Wake", "UM"],
  ["(GMT+13:00) Enderbury", "Pacific/Enderbury", "UM"],

  ["(GMT-03:00) Montevideo", "America/Montevideo", "UY"],
  ["(GMT+05:00) Tashkent", "Asia/Tashkent", "UZ"],
  ["(GMT+11:00) Efate", "Pacific/Efate", "VU"],
  ["(GMT+02:00) Rome", "Europe/Rome", "VA"],
  ["(GMT-04:00) Caracas", "America/Caracas", "VE"],
  ["(GMT+07:00) Hanoi", "Asia/Saigon", "VN"],
  ["(GMT-04:00) Port of Spain", "America/Port_of_Spain", "VG"],
  ["(GMT-04:00) Port of Spain", "America/Port_of_Spain", "VI"],
  ["(GMT+12:00) Wallis", "Pacific/Wallis", "WF"],
  ["(GMT+01:00) El Aaiun", "Africa/El_Aaiun", "EH"],
  ["(GMT+03:00) Riyadh", "Asia/Riyadh", "YE"],
  ["(GMT+02:00) Maputo", "Africa/Maputo", "ZM"],
  ["(GMT+02:00) Maputo", "Africa/Maputo", "ZW"]
]

TimeZone.delete_all
Country.delete_all

country_list.each do |name, value|
  Country.create( name: name, value: value )
end

time_zone_list.each do |name, value, value_country|
  TimeZone.create( name: name, value: value, country_id: Country.find_by(value: value_country).id )
end
